#15 - 상품 API 기능
shophubkr/shophub-server pull request #23
Opened 2023-09-29 04:41 UTC by Longstick0

## 관련 이슈
- #15 
- #16 

<br/>

## 구현한 내용 또는 수정한 내용
- 상품 API 개발
- 이미지 업로드 API 추가

<br/>

## 추가적으로 알리고 싶은 내용
- 이미지 업로드를 상품 API 안에서 같이 처리 하려다가 삽질이 좀 오래 걸리는 바람에 조금 늦어졌습니다.. 이미지 업로드를 별도 API로 빼내면 간단히 해결될 문제였는데 말이죠..
- 그래서 리뷰 코드 양이 조금 많아졌습니다..!

<br/>

## TODO / 고민하고 있는 것들
- 이미지 업로드 테스트 코드

<br/>

## 배포 Checklist
 
- [X] SecretKey 를 업데이트 해주세요
- [X] 본인을 Assign 해주세요.
- [X] 본인을 제외한 백엔드 개발자를 리뷰어로 지정해주세요.

<br/>

2023-09-29 06:28 UTC, Taaate requested changes
고생하셨습니다. 
보안이 필요한 부분이 있습니다. 확인해주시고 수정 부탁드려요!

2023-09-29 06:28 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/product/controller/ProductController.kt
> +        return productService.createProduct(
상품 등록 요청을 하는 주체와 매장의 주인이 같은지 검증하는 로직이 필요할 것 같습니다.

2023-09-29 06:28 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/product/controller/ProductController.kt
> +        val productList = productService.getProductList(pageable)
피그마 참고했을 때 상품 목록을 조회하는 경우는 매장 내의 모든 상품을 조회하는 경우만 있는 것 같습니다.
url에 shopId를 받아서 해당 매장의 상품을 조회하는 조건을 추가 해야할 것 같습니다.

2023-09-29 06:28 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/product/model/category/ProductDetailCategory.kt
> +class ProductDetailCategory (
ProductDetailCategory 랑 나중에 만들어질 subCategory랑 겹치는 느낌인데 
각각 어떤 이유로 작성된건가요?

2023-09-29 06:28 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/product/model/product/Product.kt
> +        category = null,
CreateRequest 에 categoty 값을 받는데 여기에는 null로 들어가나요??

2023-09-29 06:28 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/product/model/product/Product.kt
> +    @OneToMany(mappedBy = "product", cascade = [CascadeType.ALL], orphanRemoval = true)
@OneToMany 연관관계를 가지고 있는 엔티티들이 추가될 때
Product가 가지고 있는 리스트에는 업데이트가 되지 않는것 같습니다.

2023-09-29 06:28 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/product/service/ProductService.kt
> +        }
생성된 태그들이 product 에도 업데이트가 되어야 할 것 같습니다.

2023-09-29 06:28 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/product/service/ProductService.kt
> +        }
위와 같습니다.

2023-09-29 06:28 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/product/dto/ProductResponse.kt
> +        topCategory = product.category!!.name,
category null가능을 제거하면 !!도 제가 가능할 듯 합니다.

2023-09-29 11:33 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/product/controller/ProductController.kt
> +        return productService.createProduct(
바로 추가하겠습니다👍

2023-09-29 11:38 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/product/model/category/ProductDetailCategory.kt
> +class ProductDetailCategory (
ProductDetailCategory 리스트를 변수명으로 subCategory로 받은 것일 뿐, 같은 겁니다. 아직 MVP에서는 서브 카테고리가 요구사항에 없어 잠시 주석으로 처리해뒀습니다. 변수명과 클래스명을 일치할 필요가 있을 것 같네요.

2023-09-29 11:46 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/product/model/product/Product.kt
> +        category = null,
```java
private fun saveCategory(
        createProductRequest: CreateProductRequest,
        product: Product
    ) {
        val productCategory = ProductCategory(
            name = createProductRequest.category,
            product = product,
        )
        productCategoryRepository.save(productCategory)
        product.category = productCategory
    }
```
Category를 생성하기 위해 null로 두고, 이후에 위 코드에서 다시 값을 받습니다.

2023-09-29 12:24 UTC, Taaate approved these changes
고생하셨습니다!

2023-10-01 17:49 UTC, sectionr0 reviewed
추후 로그인 쪽 붙으면 상품 등록 때 셀러만 가능하도록 추가해주세요!

2023-10-01 17:49 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/product/service/ProductService.kt
> +        ?: throw IllegalArgumentException("매장 정보를 찾을 수 없습니다."))
ResourceNotFoundException 로 변경해주세요! 404가 뜨는게 더 좋은 것 같습니다!

2023-10-01 17:49 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/product/repository/ProductRepository.kt
> +            "WHERE p.id = :productId AND p.deleted = false")
Query어노테이션 사용하실때 아래와 같이 사용하면 보기 더 편할 것 같아요!

```kotlin

    @Query(
        """
        SELECT p
        FROM Product p
        JOIN FETCH p.images
        JOIN FETCH p.category
        JOIN FETCH p.shop
        WHERE p.id = :productId AND p.deleted = false
        """
    )

```

2023-10-01 17:49 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/product/repository/ProductRepository.kt
> +    fun findByIdAndDeletedIsFalse(productId: Long): Product?
상품 조회 시 이미지를 여러개 등록해도 이미지가 한 개만 조회되고 있는데 의도하신걸까요??

2023-10-01 18:02 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/product/repository/ProductRepository.kt
> +    fun findByIdAndDeletedIsFalse(productId: Long): Product?
의도 하셨다면 상품 상세 보기 api 도 있어야 될 것 같습니다!

2023-10-02 07:10 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/product/service/ProductService.kt
> +        ?: throw IllegalArgumentException("매장 정보를 찾을 수 없습니다."))
아하 그게 더 좋겠네요, 감사합니다!

2023-10-02 07:57 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/product/repository/ProductRepository.kt
> +    fun findByIdAndDeletedIsFalse(productId: Long): Product?
넵! 추가하겠습니다. 추가로 의도한 것이 맞습니다. 스프레드시트 MVP 에는 대표이미지로 적혀있어서 이미지 한 장으로 생각했었습니다!

2023-10-02 07:59 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/product/repository/ProductRepository.kt
> +            "WHERE p.id = :productId AND p.deleted = false")
하나 또 알아갑니다..ㅎㅎ

2023-10-03 07:01 UTC, merged