#26 - 유저 도메인 개발
shophubkr/shophub-server pull request #29
Opened 2023-10-03 13:12 UTC by Taaate

## 관련 이슈
- #26 

<br/>

## 구현한 내용 또는 수정한 내용
- 이메일 인증 개발 
  - 이벤트리스너를 통해서 회원가입 시점에 바로 메일 전송
- 비밀번호 찾기 개발
- 유저 정보 변경 개발
- 마이페이지 개발
  - 팔로우와 쿠폰이 개발되어야 완성 가능 

<br/>

## 추가적으로 알리고 싶은 내용
- 메일서비스 관련해서 SecretKey가 업데이트 되었습니다!

<br/>

## TODO / 고민하고 있는 것들
- x

<br/>

## 배포 Checklist
 
- [x] SecretKey 를 업데이트 해주세요
- [x] 본인을 Assign 해주세요.
- [x] 본인을 제외한 백엔드 개발자를 리뷰어로 지정해주세요.

<br/>

2023-10-05 18:54 UTC, sectionr0 requested changes

2023-10-05 18:54 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/global/exception/ExceptionUtil.kt
> +    throw IllegalArgumentException("유저를 찾을 수 없습니다.")
404로 처리하는 게 더 좋아보입니다!

2023-10-05 18:54 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
> +            return CheckResponse("비밀번호가 일치하지 않습니다!")
비밀번호가 일치하지 않을 때는 200대 응답보다는 400대 에러로 처리하는게 더 좋을 것 같습니다!

2023-10-05 18:54 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/user/dto/CheckResponse.kt
> +    val result: String,
저희가 공통 응답으로 result를 감싸서 주는데, 여기서 result를 한번 더 감싸면 중복되는 느낌인데 다른 걸로 바꾸거나 응답값을 없애는 건 어떠신가요?

2023-10-05 18:54 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/user/controller/UserController.kt
> +    }
해당 컨트롤러는 닉네임과 비밀번호를 같이 업데이트를 할 때 사용하는 건가요? 
닉네임만 따로 업데이트는 못하는 걸까요??

2023-10-05 18:54 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
> +    }
dto 로 이메일 값을 받아서 해당 정보로 유저를 찾은 후 업데이트를 하고 있는데, 다른 사람의 이메일을 입력하면 보안 상문제가 있을 것 같습니다! 수정 부탁드립니다!

2023-10-06 04:30 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/user/controller/UserController.kt
> +    }
<img width="307" alt="스크린샷 2023-10-06 오후 1 29 38" src="https://github.com/shophubkr/shophub-server/assets/83914354/6cfa166c-03b5-4e0b-a607-0299ff4042a4">

피크마에 이렇게 나와있어서 우선 로직을 그렇게 작성했습니다.
만약 제가 기획분들께 물어봐서 나누거나 유지하도록 해보겠습니다!

2023-10-06 04:38 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
> +    }
이 부분은 조금 문제가 있겠네요.
해당 로직은 비밀번호을 까먹어서 재설정하기 위한 로직입니다. (피그마 비밀번호 찾기 부분)
그럼 유저가 작성한 이메일이 정말 본인의 이메일인지 확인할 수 있는 방법이 없을 것 같습니다.
아니면 1차로 이메일 인증일 실시하고, 이메일 인증에 통과되었다면 해당 메일로 비밀번호 재설정 링크를 보내주어야 할 것 같은데
이 부분도 기획분들께 물어보겠습니다.

2023-10-06 06:22 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
> +    }
질문 결과 : 메일이 전송된 메일함을 확인하려면 해당 도메인에(ex 네이버 메일함) 로그인 해야하니까 보안상에 문제가 되지는 않을 것 같습니다!

2023-10-06 06:23 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/user/controller/UserController.kt
> +    }
질문 결과: 수정 사항을 하나의 폼으로 처리하고 싶으시다고 합니다. 만약 값을 채우지 않으면 따로 수정되지 않는 것으로 처리하겠습니다.

2023-10-06 11:39 UTC, Longstick0 reviewed
고생 많으셨습니다! 쿠폰 API 도 서둘러 개발 완료하겠습니다.

2023-10-06 11:39 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/ShopHubApplication.kt
> +@EnableAsync
저번에 Slack 오류 알림 쪽 개발 하면서 ThreadPoolConfig 클래스에 @EnableAsync 어노테이션을 붙여 놨는데요.
찾아보니까 충돌이 나거나 상위 패키지 클래스의 설정만 적용되는 건 없다고 합니다. 하지만 코드 조직화 관점에서 ThreadPoolConfig에서만 관리하는 게 어떨까요?

2023-10-06 11:39 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/global/event/EventListener.kt
> +    fun sendJoinMail(event: JoinEvent) {
별도의 스레드 설정을 하지 않으면 SimpleAsyncTaskExecutor로 스레드가 관리되는데, 이는 이메일을 보내야 하는 요청이 매우 많이 들어와 스레드풀에 계속 스레드를 생성하고 삭제해야 돼서 특정 상황에 리소스가 부족할 수도 있을 것 같습니다. 혹시 제가 놓친 부분이 있다면 말씀해주시면 감사하겠습니다.

2023-10-06 11:39 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/global/jwt/service/JwtService.kt
> +        const val TEN_MINUTE = 3600000
나중에 10분으로 다시 바꿔주세요.

2023-10-06 11:39 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/user/service/AuthService.kt
> +        val socialUser = userRepository.findByEmail(email) ?: failFindingUser()
이를 ExceptionUtil로 빼내어 분리하신 이유가 궁금합니다! 다른 엔티티 서비스에서도 ExceptionUtil에서 가져와 적용한다고 했을 때 그대로 ExceptionUtil에 추가하여 처리할 계획인가요? 

잘못되었다는 건 아니고, 생각하신 근거가 궁금해서요.

2023-10-06 11:39 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/user/service/MailService.kt
> +        val link = "비밀번호 재설정용 링크"
아직 미완성된 부분인가요?

2023-10-06 11:44 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/user/service/AuthService.kt
> +        val socialUser = userRepository.findByEmail(email) ?: failFindingUser()
서비스 계층과 여러 부분에서 유저 찾기에 실패했을 때마다 비슷한 에러 발생이 중복 된다고 생각해서
하나의 클래스에서 처리해주면 좋겠다고 생각했습니다.

2023-10-06 11:45 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/jwt/service/JwtService.kt
> +        const val TEN_MINUTE = 3600000
테스트 용으로 1시간으로 설정해두고 까먹었습니다.
나중에 수정해두겠습니다.

2023-10-06 11:46 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/user/service/MailService.kt
> +        val link = "비밀번호 재설정용 링크"
네네 메일의 양식?에 대해서 제가 잘 몰라서
다음 스프린트때 의견을 나누고 정하면 좋을 듯 합니다!

2023-10-06 11:59 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/ShopHubApplication.kt
> +@EnableAsync
수정했습니다.

2023-10-06 11:59 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/event/EventListener.kt
> +    fun sendJoinMail(event: JoinEvent) {
내용 찾아보고 Config에 등록된 빈의 쓰레드를 사용하도록 수정했습니다.

2023-10-07 06:24 UTC, Longstick0 approved these changes

2023-10-07 07:27 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
> +    }
혹시 비밀번호 재설정 메일을 통해서 입력받는 폼을 말씀하신 거라면 나중에 인증 메일과 비밀번호 재설정 메일 작업이 완료되면
그때 적절한 링크를 생성해서 발신자의 메일을 포함한 토큰을 같이 전송하도록 만들면 될 것 같습니다.

2023-10-08 09:49 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/user/service/MailService.kt
> +        val link = "http://localhost:8081/api/v1/auth/authorize?token=$token"
localhost 부분 ${baseUrl}로 변경 해주세요!
그리고 인증 이메일인지, 비밀번호 재설정인지 url 이름을 변경해주시면 더 좋을 것 같아요

2023-10-08 09:49 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/user/controller/UserController.kt
> +    fun checkPassword(@RequestBody password: PasswordRequest): CommonResponse<String> {
String 보다는 EmptyDto로 처리하는 게 더 좋아보입니다..! 저희가 모든 응답을 객체로 감싸서 내려주고 있고, 메시지를 내려주는 것도 좋지만, 메시지 경우에는 에러일 때 주로 내려주면 좋을 것 같습니다.
성공한 경우에는 200 응답이랑 빈 객체 또는 userId 등 객체로 감싸서 내리는 게 더 좋아보입니다!

2023-10-08 10:23 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/user/service/MailService.kt
> +        val link = "http://localhost:8081/api/v1/auth/authorize?token=$token"
일단 스트링 변수로 놨는데, 나중에 도메인 주소 결정되면 환경설정 별로 변수로 뽑아서 처리하면 좋을 것 같습니다!

2023-10-08 10:24 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/user/controller/UserController.kt
> +    fun checkPassword(@RequestBody password: PasswordRequest): CommonResponse<String> {
200 + 빈 응답으로 수정했습니다!

2023-10-08 12:28 UTC, sectionr0 approved these changes

2023-10-08 12:29 UTC, sectionr0 commented
고생하셨습니다!👍

2023-10-09 00:18 UTC, merged