#27 - 매장 팔로우 구현
shophubkr/shophub-server pull request #30
Opened 2023-10-09 06:25 UTC by Taaate

## 관련 이슈

- #27 

<br/>

## 구현한 내용 또는 수정한 내용

- 매장 팔로우
  - 처음 팔로우시 팔로우 / 다시 누르면 언팔로우
- 팔로우한 매장 리스트 조회
- 유저 메인 화면에 팔로우한 매장 목록이 나오도록 수정

<br/>

## 추가적으로 알리고 싶은 내용
- 

<br/>

## TODO / 고민하고 있는 것들
- 

<br/>

## 배포 Checklist
 
- [x] SecretKey 를 업데이트 해주세요
- [x] 본인을 Assign 해주세요.
- [x] 본인을 제외한 백엔드 개발자를 리뷰어로 지정해주세요.

<br/>

2023-10-09 06:49 UTC, Taaate commented
생각해보니 쿠폰 파티가 머지 되면 마이페이지 부분에 쿠폰도 업데이트 되어야 합니다.
우선 그 부분은 감안하고 리뷰 부탁드립니다! 
나중에 머지하기전에 업데이트 하겠습니다!

2023-10-10 12:07 UTC, sectionr0 requested changes
팔로우 수 가져오는 정보 필요할 것 같습니다!

2023-10-10 12:07 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/follow/service/FollowService.kt
> +
Deleted 붙여주시고 failFindingShop 제거 부탁드립니다!

2023-10-11 05:35 UTC, sectionr0 approved these changes

2023-10-11 05:35 UTC, sectionr0 commented
고생하셨습니다!

2023-10-11 06:07 UTC, Longstick0 approved these changes
고생하셨습니다!

2023-10-11 06:07 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/follow/repository/FollowRepository.kt
> +    @Modifying(flushAutomatically = true)
@sectionr0, 기천님, 태호님이 작성하신 이 부분을 보고 든 생각인데요, 저희가 softDelete를 통해 데이터를 완전히 삭제하는 게 아니라 isDeleted의 상태값만 바꾸어 처리를 하잖아요? 그런데, softDelete를 하지 않고 flush 처리하지 않는다면 나중에 조회에서 삭제된 데이터를 조회해오는 상황이 발생하지 않을까 생각이 듭니다. 혹시 어떻게 생각하시나요?

2023-10-11 06:20 UTC, merged