#28 - 쿠폰 API 기능 개발
shophubkr/shophub-server pull request #31
Opened 2023-10-11 05:28 UTC by Longstick0

## 관련 이슈

- #28 

<br/>

## 구현한 내용 또는 수정한 내용
- (buyer)
- 쿠폰 발행 목록 확인
- 쿠폰 발급
- 쿠폰 사용
- (seller)
- 쿠폰 목록 확인
- 쿠폰 등록
- 쿠폰 조기 종료

<br/>

## 추가적으로 알리고 싶은 내용
X

<br/>

## TODO / 고민하고 있는 것들
X
<br/>

## 배포 Checklist
 
- [X] SecretKey 를 업데이트 해주세요
- [X] 본인을 Assign 해주세요.
- [X] 본인을 제외한 백엔드 개발자를 리뷰어로 지정해주세요.

<br/>

2023-10-11 06:06 UTC, AnTaeho requested changes
확인 부탁드립니다!

2023-10-11 06:06 UTC, AnTaeho commented on src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
> +    fun getMyCoupons(userId: Long, status: UserCouponCond): UserCouponListResponse{
이 부분 페이징 처리랑 총 쿠폰수가 필요할 것 같습니다!

2023-10-11 06:06 UTC, AnTaeho commented on src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
> +        user.userCoupon.add(saveUserCoupon)
이런 연관관계 편의 메서드는 해당 객체 내부에서 처리하는게 좋을 듯 합니다.
현재 user.getUserCoupon().add(~~) 이런 느낌이라
user.addUserCoupon() 같은 방식으로 처리하는건 어떨까요

2023-10-11 06:06 UTC, AnTaeho commented on src/main/kotlin/kr/co/shophub/shophub/user/repository/UserCouponCustomRepositoryImpl.kt
> +    private fun couponSearchCond(status: UserCouponCond): BooleanExpression =
이 부분은 기획분들과 상의가 필요할 듯 한데, 
굳이 기간이 만료된 쿠폰을 확인 하는 것이 필요할까 생각됩니다. 
사용 가능 / 사용 불가능 정도로 나눈건 어떨까 생각합니다.
한번 기획분들에게 물어보시고 결정해주세요!

2023-10-11 06:06 UTC, AnTaeho commented on src/main/kotlin/kr/co/shophub/shophub/user/repository/UserCouponCustomRepositoryImpl.kt
> +    ): List<UserCoupon>{
페이징 처리가 필요할 것 같습니다!

2023-10-11 06:06 UTC, AnTaeho commented on src/main/kotlin/kr/co/shophub/shophub/coupon/controller/CouponController.kt
> +    @PostMapping("/{shopId}/coupon")
url을 /coupon/{shopId}로 변경하는건 어떤가요?
그럼 RequestMapping에 공통적으로 처리할 수 있을 것 같습니다.

2023-10-11 06:06 UTC, AnTaeho commented on src/main/kotlin/kr/co/shophub/shophub/coupon/repository/CouponRepository.kt
> +    fun findByCouponIdAndDeletedIsFalse(couponId: Long): Coupon
이거 null일 확률도 있는거 같습니다!

2023-10-11 06:24 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/user/service/UserService.kt
> +    fun getMyCoupons(userId: Long, status: UserCouponCond): UserCouponListResponse{
넵 수정하겠습니다!

2023-10-11 06:31 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/user/repository/UserCouponCustomRepositoryImpl.kt
> +    private fun couponSearchCond(status: UserCouponCond): BooleanExpression =
저도 비슷하게 고민하던 부분입니다. 하지만 사용 불가능에도 만료된 것인지, 이미 사용해서 사용을 못하는지의 정보는 제공해줘야 한다고 생각이 듭니다! 좀 더 고민해보겠습니다.

2023-10-11 06:32 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/coupon/controller/CouponController.kt
> +    @PostMapping("/{shopId}/coupon")
이 부분도 고민을 했던 부분이긴 합니다! 처음에는 '매장의 쿠폰' 이라는 느낌이 강해 위와 같이 작성했는데, 다시 보니 말씀하신 방법이 더 나아 보이네요.

2023-10-11 07:56 UTC, sectionr0 requested changes

2023-10-11 07:56 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/coupon/service/CouponService.kt
> +    }
예외처리 해주세요!

2023-10-11 07:56 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/coupon/repository/CouponRepository.kt
> +        JOIN FETCH c.shop
상점 정보를 가져오는 이유가 있을까요??

2023-10-11 07:56 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/coupon/service/CouponService.kt
> +class CouponService(
해당 서비스에 @Transactional 부분 중복된 것들이 있는데 확인해주세요

2023-10-11 07:56 UTC, sectionr0 commented on src/main/resources/application-local.yml
> +      ddl-auto: update
local 부분은 특별한 경우가 아니라면 변경하지 말아주세요!

2023-10-11 13:34 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/coupon/repository/CouponRepository.kt
> +        JOIN FETCH c.shop
CouponService의 terminateCoupon에서 매장의 권한을 체크할 때 사용합니다!

2023-10-11 13:35 UTC, Longstick0 commented on src/main/kotlin/kr/co/shophub/shophub/coupon/service/CouponService.kt
> +    }
넵! 수정 완료했습니다.

2023-10-11 13:37 UTC, Longstick0 commented on src/main/resources/application-local.yml
> +      ddl-auto: update
엇 이 부분은 실수로 잘못 푸시해버렸네요.. 다음에 신경 쓰겠습니다!

2023-10-12 02:12 UTC, sectionr0 approved these changes

2023-10-12 02:34 UTC, Taaate approved these changes
고생하셨습니다!

2023-10-18 13:23 UTC, merged