[ShopHub/4] 회원 가입 / 로그인 구현 (+ JWT)
shophubkr/shophub-server pull request #6
Opened 2023-08-17 06:39 UTC by Taaate

## 관련 이슈
 - #4 
 - 회원 가입 + 로그인과 JWT 부분을 나누려다가 서로 엮여 있는 부분이 많아서 한번에 구현 했습니다. 코드가 530줄로 생각보다 많아 졌는데,
    제가 한번 코드를 설명해 드리는 시간이 있으면 두 분 다 이해하기 편할 것 같습니다!

## 구현한 내용 또는 수정한 내용
 - 일반 회원 가입 구현
 - 폼 형식의 로그인 구현 (RequestBody를 사용)
 - JWT를 사용한 인증 구현

## TODO / 고민중인 내용
 - 회원 로그인 구현
   - 소셜 로그인

## 배포 CheckList
 - jwt 관련 yml 파일이 잘 담기는지 확인 해야함

2023-08-18 03:43 UTC, Taaate commented on .github/workflows/ci.yml
> +      - name: Set up jwt yml file
빌드 할 때 jwt 관련 변수를 담은 yml을 gitignore 해두고 secrets에 넣어 두었습니다.

2023-08-18 03:45 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/config/SecurityConfig.kt
> +
SpringBoot3 버전 이상부터 바뀐 부분이 좀 있어서 공식문서 찾아보고 이래저래 검색 해보고 작성했습니다.

2023-08-18 04:38 UTC, Taaate reviewed
설명이 필요 할 것 닽아서 리뷰 형식으로 코멘트를 남겼습니다. 
두 분 확인해 주시고 의견 주세요!

2023-08-18 04:38 UTC, Taaate commented on .github/workflows/ci.yml
> -
MySQL 을 추가하는 것은 결국 필요가 없어서 지우고
application-jwt.yml 파일을 gitignore 설정해 둬서 시크릿에 저장해 두고 가져오는 코드를 추가했습니다!

2023-08-18 04:38 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/config/SecurityConfig.kt
> +
SpringBoot3.x로 넘어오면서 SecurityConfig 관련 문법이 많이 변했습니다. 
관련 내용 최대한 공식 문서 참고해서 작성했습니다. 
세부적인 설명은 각 클래스에서 자세하게 하겠습니다.

2023-08-18 04:38 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/jwt/filter/JwtAuthenticationProcessingFilter.kt
> + */
로그인 요청외의 요청이 오면 해당 필터를 거치게 됩니다.
해당 필터는 JWT 검증을 맡습니다.

요청 헤더에 RefreshToken의 포함 유무에 따라 서로 다른 방식으로 진행 됩니다.
기본적으로 AccessToken 만 요청에 포함됩니다. 해당 토큰이 유효하다면 로그인 된 상태입니다.
AccessToken 이 만료 되면 RefreshToken을 포함해서 요청을 보냅니다. refreshToken이 유효하다면 
다른 인증 절차 없이(로그인과 같은) AccessToken과 RefreshToken을 재발급 합니다.

RefreshToken도 만료가 됐다면 다시 인증 절차를 밟아야 합니다.

2023-08-18 04:38 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/jwt/service/JwtService.kt
> + */
JWT 와 관련된 거의 모든 로직이 있는 서비스 입니다.
다른 요소는 그렇게 중요하지 않지만 secretKey는 JWT를 해석할 수 있는 중요한 정보라 yml파일에 따로 저장해 두었습니다.
해당 yml 파일은 노션에 정리해 두었습니다.

2023-08-18 04:38 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/jwt/service/JwtService.kt
> +
AccessToken을 발급할 땐 email을 담아 둡니다. 
email 인증을 거치기 때문에 유저를 식별하는 요소로 적당하다고 생각했습니다. 
필요하다면 다른 정보도 추가할 수 있지만 보안상 민감한 정보는 최소화하는게 좋다고 알고 있습니다.

2023-08-18 04:38 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/jwt/util/PasswordUtil.kt
> +
랜덤한 8자리 비밀번호는 만들어 주는 클래스입니다.
jwt 토큰엔 민감한 정보(유저의 비밀번호)를 담지 않는데, 인증된 사용자의 UserDetails 객체를 만들기 위해선 비밀번호가 필요합니다.
어차피 email을 통한 식별만 이루어 지기 때문에 UserDetauls에 담기는 비밀번호는 임의의 랜덤한 문자열로 정했습니다.

2023-08-18 04:38 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/login/filter/CustomJsonUsernamePasswordAuthenticationFilter.kt
> +
"/login" + POST 요청일 때 동작하는 필터입니다.

해당 클래스에선 인증용 객체를 만드는 역할을 합니다.
인증 절차는 SecurityConfig에서 설정해준 authenticationManager에서 처리합니다. 
자세한 설명은 SecurityConfig에서 하겠습니다.

2023-08-18 04:38 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/config/SecurityConfig.kt
> +
커스텀 로그인 필터에서 사용하는 인증용 처리 객체입니다.
DaoAuthenticationProvider는 AuthenticationProvider의 구현체입니다.

해당 객체는 UserDetailsService와 PasswordEncoder를 사용하기 때문에 선택했습니다.
참고로 회원 가입 과정에서 문제가 없다면 비밀번호를 PasswordEncoder로 인코딩해서 저장합니다.

2023-08-18 04:38 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/login/handler/LoginSuccessHandler.kt
> +
로그인에 성공했을 때 거치게 되는 핸들러입니다.
인증객체에서 이메일을 찾아 토큰을 생성해주고, 응답 헤더에 담아 줍니다.

2023-08-18 04:38 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/login/service/LoginService.kt
> +
UserDetailsService 의 커스텀 객체입니다.
DaoAuthenticationProvider 에서 사용됩니다.

2023-08-18 04:38 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/user/controller/dto/SignUpRequest.kt
> +
피그마를 확인해보니 셀러일 경우 전화번호를 입력합니다.
유저 객체에 저장을 해야할 듯 한데, 일단 당장은 추가하지 않았습니다. 
두 분 의견 남겨주시면 감사하겠습니다!

2023-08-18 13:47 UTC, Longstick0 approved these changes
**👍고생하셨습니다!** 저도 사실 이 부분은 같이 프로젝트 하기 전에 봤던 부분들이라 크게 코멘트 없이 훑어봤습니다.

2023-08-19 07:06 UTC, sectionr0 reviewed
sign-up 오류 시 403 오류 뜨고 있는데 다른 에러코드로 내려주는게 맞을 것 같습니다!

2023-08-19 07:06 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/user/controller/UserController.kt
> +    fun signUp(@RequestBody request: SignUpRequest): User = userService.signUp(request)
User Entity를 직접 외부로 노출하는 것은 좋지 않은 것 같습니다..! 
따로 Dto 만들어서 필요한 정보만 보여주면 좋을 것 같습니다

2023-08-19 07:06 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/global/jwt/service/JwtService.kt
> +    fun sendAccessAndRefreshToken(
토큰 응답을 response 대신 Header로 설정하신 이유가 있으실까요??

2023-08-19 07:06 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/global/jwt/filter/JwtAuthenticationProcessingFilter.kt
> +        val password = PasswordUtil.generateRandomPassword()
UserDetails 에는 임시 비밀번호를 생성하는건가요??

2023-08-19 07:06 UTC, sectionr0 commented on src/main/kotlin/kr/co/shophub/shophub/global/login/handler/LoginFailureHandler.kt
> +        response.contentType = "text/plain;charset=UTF-8"
text 형식보다 Json 형식으로 내리는 것이 좋을 것 같습니다!

2023-08-19 07:12 UTC, sectionr0 requested changes
회원가입은 sign-up으로 되어 있는데 
로그인은 Login 으로 이름이 정해져있는데,
sign-in 은 어떠신가요? 

sign-up <> sign-in
join <> login

이 형식이 조금 더 통일성 있는 것 같습니다

2023-08-19 07:14 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/user/controller/UserController.kt
> +    fun signUp(@RequestBody request: SignUpRequest): User = userService.signUp(request)
그렇게 했어야 했는데 놓쳤습니다! 수정 해두겠습니다!

2023-08-19 07:16 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/jwt/filter/JwtAuthenticationProcessingFilter.kt
> +        val password = PasswordUtil.generateRandomPassword()
맞습니다. 
jwt 토큰엔 민감한 정보가 포함되면 안되는데, 해당 과정에서 jwt 만으로 UserDetails 객체를 만들어야 해서 
passwordUtil을 통해서 임의의 비밀번호를 생성해 객체를 만들었습니다.

2023-08-19 07:18 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/jwt/service/JwtService.kt
> +    fun sendAccessAndRefreshToken(
<img width="908" alt="스크린샷 2023-08-19 오후 4 18 10" src="https://github.com/shophubkr/shophub-server/assets/83914354/024e14e6-d33a-4b2e-90c5-e3d948dfa684">

response 헤더에 담아서 넘겨줍니다!

2023-08-19 07:19 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/login/handler/LoginFailureHandler.kt
> +        response.contentType = "text/plain;charset=UTF-8"
수정 해두겠습니다!

2023-08-19 07:22 UTC, Taaate commented
시큐리티 로그인 기본 url인 "/login"을 유지하려 했습니다.
그럼 회원가입을 join으로 수정해서 형식을 통일해 보겠습니다!

2023-08-20 05:00 UTC, Taaate commented on src/main/kotlin/kr/co/shophub/shophub/global/login/handler/LoginFailureHandler.kt
> +        response.contentType = "text/plain;charset=UTF-8"
<img width="497" alt="스크린샷 2023-08-20 오후 1 59 52" src="https://github.com/shophubkr/shophub-server/assets/83914354/b30c7cef-473d-421d-934b-bebd296ab476">

다음과 같이 변경 했습니다. 필요하다면 정보를 수정 / 추가 할 수 있습니다.

2023-08-21 14:06 UTC, closed without merging